version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: psql
      POSTGRES_DB: pizza
    ports:
      - 5432:5432

  backend:
    build: backend
    command: npm start
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    depends_on:
      - db
    ports:
      - 3010:3000

  frontend:
    build:
      context: ./frontend
    ports:
      - '3020:80'
